version: '2.1'

services:
  users-service:
    container_name: users-service
    build: ./services/users/
    volumes:
      - './services/users:/usr/src/app'
      - './services/users/package.json:/usr/src/package.json'
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@users-db:5433/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5433/users_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=changeme
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
  mockups-service:
    container_name: mockups-service
    build: ./services/mockups/
    volumes:
      - './services/mockups:/usr/src/app'
      - './services/mockups/package.json:/usr/src/package.json'
    ports:
      - '8081:8080'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@mockups-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@mockups-db:5432/users_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=changeme
    depends_on:
      mockups-db:
        condition: service_healthy
    links:
      - mockups-db
  users-db:
    container_name: users-db
    build: ./services/users/src/db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: exit 0
  mockups-db:
    container_name: mockups-db
    build: ./services/mockups/src/db
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: exit 0
  web-service:
    container_name: web-service
    build: ./web/
    volumes:
      - './web:/usr/src/crawlr'
      - '/usr/src/crawlr/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      users-service:
        condition: service_started
      mockups-service:
        condition: service_started
    links:
      - users-service
      - mockups-service
